let sources = import ./nix/sources.nix; # generated by niv
    pkgs = import sources.nixpkgs { };
in
pkgs.mkShell {
  # nativeBuildInputs is usually what you want -- tools you need to run
  nativeBuildInputs = with pkgs.buildPackages;
    [
      niv
      
      ocamlPackages.ocaml
      ocamlPackages.dune_3
      ocamlPackages.findlib
      ocamlPackages.utop
      ocamlPackages.odoc
      ocamlPackages.ocaml-lsp
      ocamlPackages.ocamlformat

      ocamlPackages.cmdliner

      ocamlPackages.janeStreet.base
      ocamlPackages.janeStreet.sexplib
      ocamlPackages.janeStreet.ppx_jane
    ];
}
